name: CI Code Checks
on: [pull_request, workflow_dispatch]
jobs:
  build:
    name: code checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync --extra dev
        uv run python -m nltk.downloader stopwords

    - name: Checking formatting and linting with ruff
      run: uv run make lint

    - name: Type checking with mypy
      run: uv run make typing

    - name: Running tests
      run: uv run make test

    - name: Creating coverage folder
      run: mkdir -p coverage

    - name: Coverage Badge
      run: |
        uv run pip install genbadge[coverage]
        uv run coverage xml
        uv run genbadge coverage -i coverage.xml -o coverage/coverage.svg

    - name: Publish coverage report to coverage-badge branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: coverage
